import numpy as np

RELATIVE_STRIKE_UPPER_BOUND= 1.2
RELATIVE_STRIKE_LOWER_BOUND= 0.8
NUMBER_OF_STRIKES= 50
strike_range = np.linspace(RELATIVE_STRIKE_LOWER_BOUND,RELATIVE_STRIKE_UPPER_BOUND,NUMBER_OF_STRIKES)
S_OVER_K_RANGE= np.array([1/K for K in strike_range[::-1]])
PRECISION = 0.01
MAX_ITER = 30
